// ----------------------
// <auto-generated>
//     Generated using my buggy toolchain - see: scripts/pre-build-tasks
// </auto-generated>
// ----------------------

export const MessageKeys = {
  trading: {
    trade: 'trading.trade',
    asset: 'trading.asset',
    investment: 'trading.investment',
    newTrade: 'trading.newTrade',
    opened: 'trading.opened',
    closed: 'trading.closed',
    entryPrice: 'trading.entryPrice',
    exitPrice: 'trading.exitPrice',
    stopLoss: 'trading.stopLoss',
    takeProfit: 'trading.takeProfit',
    currency: 'trading.currency',
    profitLoss: 'trading.profitLoss',
    profit: 'trading.profit',
    loss: 'trading.loss',
    size: 'trading.size',
    reference: 'trading.reference',
    results: {
      result: 'trading.results.result',
      loss: 'trading.results.loss',
      breakEven: 'trading.results.breakEven',
      mediocre: 'trading.results.mediocre',
      win: 'trading.results.win',
      determineAutomatically: 'trading.results.determineAutomatically',
    },
    notes: 'trading.notes',
  },
  appearance: 'appearance',
  language: 'language',
  profile: 'profile',
  settings: 'settings',
  userSettings: 'userSettings',
  logout: 'logout',
  login: 'login',
  underConstruction: 'underConstruction',
  copied: 'copied',
  entryNotFound: 'entryNotFound',
  oopsSomethingWentWrong: 'oopsSomethingWentWrong',
  unexpectedErrorOccured: 'unexpectedErrorOccured',
  technicalDifficulties: 'technicalDifficulties',
  retry: 'retry',
  environment: 'environment',
  name: 'name',
  version: 'version',
  initialLoadingTitle: 'initialLoadingTitle',
  initialLoadingDescription: 'initialLoadingDescription',
  thanksForYourPatience: 'thanksForYourPatience',
  loadingComplete: 'loadingComplete',
  loadingTook: 'loadingTook',
  goHome: 'goHome',
  pageNotFound: 'pageNotFound',
  and: 'and',
  settingNotSaved: 'settingNotSaved',
  close: 'close',
  genericErrorMessage: 'genericErrorMessage',
  german: 'german',
  english: 'english',
  light: 'light',
  auto: 'auto',
  dark: 'dark',
  save: 'save',
  accessDenied: 'accessDenied',
  notAuthenticatedError: 'notAuthenticatedError',
  empty: 'empty',
  now: 'now',
} as const;

type ExtractStringValues<T> = T extends string
  ? T
  : T extends Record<string, unknown>
    ? ExtractStringValues<T[keyof T]>
    : never;

export type MessageKey = ExtractStringValues<typeof MessageKeys>;
