name: Continuous Deployment

on:
  push:
    tags: ['**']

jobs:
  build:
    uses: ./.github/workflows/shared-build.yaml
    with:
      node-version: '24'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: foo
        shell: pwsh
        run: |
          $Version = "${{ needs.build.outputs.version }}"
          Write-Host "Deploy Version $Version"