name: Shared Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
    outputs:
      version:
        description: "The App Version"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:

      - name: Extract version from tag
        id: extract_version
        run: |
          if ($env:GITHUB_REF -like "refs/tags/*") {
            $Version = $env:GITHUB_REF -replace 'refs/tags/', ''
          } else {
            Write-Host "No version found. Use default version instead."
            $Version = "0.0.0"
          }

          Write-Host "Version: $Version"
          echo "version=$Version" >> $env:GITHUB_OUTPUT

      - name: Validate SemVer version
        run: |
          $Version = "${{ steps.extract_version.outputs.version }}"

          if ($Version -notmatch '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$') {
            Write-Error "Version '$Version' is not a valid SemVer."
            EXIT -1
          } else {
            Write-Host "Version '$Version' is a valid SemVer. "
          }

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm install

      - name: Lint
        env:
          CI: true
        run: npm run lint

      - name: Build
        run: |
          npm version ${{ steps.extract_version.outputs.version }} --allow-same-version --no-git-tag-version
          npm run build