name: Shared Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      app-version:
        required: true
        type: string

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm install

      - name: Lint
        env:
          CI: true
        run: npm run lint

      - name: Build
        run: |
          npm version ${{ inputs.app-version }} --allow-same-version --no-git-tag-version
          npm run build